package cfg.skill;
public final class ParticleEffect extends cfg.skill.Action {
	public final static int TYPEID = -240179106;
	final public int getTypeId() { return TYPEID; }
	public final int id;
	public final int type;
	public final float fadeouttime;
	public final String path;
	public final float life;
	public final boolean followdirection;
	public final boolean followbeattackeddirection;
	public final float scale;
	public final int casterbindtype;
	public final boolean followbonedirection;
	public final int targetbindtype;
	public final int instancetracetype;
	public final float worldoffsetx;
	public final float worldoffsety;
	public final float worldoffsetz;
	public final float worldrotx;
	public final float worldroty;
	public final float worldrotz;
	public final float boneposx;
	public final float boneposy;
	public final float boneposz;
	public final float bonerotx;
	public final float boneroty;
	public final float bonerotz;
	public final float bonescalex;
	public final float bonescaley;
	public final float bonescalez;
	public final String bonename;
	public final float tracetime;
	public final int aligntype;
	public final boolean ispooldestoryed;
	public ParticleEffect(cfg.DataStream fs) {
		super(fs);
		this.id = fs.getInt();
		this.type = fs.getInt();
		this.fadeouttime = fs.getFloat();
		this.path = fs.getString();
		this.life = fs.getFloat();
		this.followdirection = fs.getBool();
		this.followbeattackeddirection = fs.getBool();
		this.scale = fs.getFloat();
		this.casterbindtype = fs.getInt();
		this.followbonedirection = fs.getBool();
		this.targetbindtype = fs.getInt();
		this.instancetracetype = fs.getInt();
		this.worldoffsetx = fs.getFloat();
		this.worldoffsety = fs.getFloat();
		this.worldoffsetz = fs.getFloat();
		this.worldrotx = fs.getFloat();
		this.worldroty = fs.getFloat();
		this.worldrotz = fs.getFloat();
		this.boneposx = fs.getFloat();
		this.boneposy = fs.getFloat();
		this.boneposz = fs.getFloat();
		this.bonerotx = fs.getFloat();
		this.boneroty = fs.getFloat();
		this.bonerotz = fs.getFloat();
		this.bonescalex = fs.getFloat();
		this.bonescaley = fs.getFloat();
		this.bonescalez = fs.getFloat();
		this.bonename = fs.getString();
		this.tracetime = fs.getFloat();
		this.aligntype = fs.getInt();
		this.ispooldestoryed = fs.getBool();
	}
}